# Generated by Django 4.2.11 on 2024-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
