# Generated by Django 4.2.11 on 2024-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0002_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
