# Generated by Django 4.2.11 on 2024-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0003_status_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("Ativo", "Ativo"),
                            ("Licença", "Licença"),
                            ("Desiste", "Desiste"),
                            ("Reforma", "Reforma"),
                        ],
                        default="Ativo",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
