# Generated by Django 4.2.11 on 2024-07-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0004_estatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estatus", old_name="estatus", new_name="Estatus",
        ),
    ]
