# Generated by Django 4.2.11 on 2024-07-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0005_rename_estatus_estatus_estatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estatus", old_name="Estatus", new_name="estatus",
        ),
    ]
