# Generated by Django 5.0.7 on 2024-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0006_rename_estatus_estatus_estatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nivel_Estudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
