# Generated by Django 4.2.11 on 2024-06-10 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionariu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nu", models.CharField(max_length=20, null=True)),
                ("naran", models.CharField(max_length=200, null=True)),
                (
                    "seksu",
                    models.CharField(
                        blank=True,
                        choices=[("Mane", "Mane"), ("Feto", "Feto")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("fatin_moris", models.CharField(max_length=200, null=True)),
                ("data_moris", models.DateField(null=True)),
                ("diresaun", models.CharField(max_length=200, null=True)),
                ("pozisaun", models.CharField(max_length=200, null=True)),
                ("hela_fatin", models.CharField(max_length=200, null=True)),
                ("nu_kontaktu", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("pdf", models.FileField(blank=True, null=True, upload_to="CV/")),
                (
                    "municipality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom.municipality",
                    ),
                ),
                (
                    "tinan_tama",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom.tinan",
                    ),
                ),
            ],
        ),
    ]
