# Generated by Django 4.2.11 on 2024-06-10 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0002_status"),
        ("dnct", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariu",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom.status",
            ),
        ),
    ]
