# Generated by Django 4.2.11 on 2024-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0002_funcionariu_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionariu",
            name="nu",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
