# Generated by Django 4.2.11 on 2024-06-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0003_alter_funcionariu_nu"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariu",
            name="data_tama",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="funcionariu",
            name="tinan_remata",
            field=models.DateField(null=True),
        ),
    ]
