# Generated by Django 4.2.11 on 2024-06-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0004_funcionariu_data_tama_funcionariu_tinan_remata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionariu", old_name="tinan_remata", new_name="data_remata",
        ),
    ]
