# Generated by Django 4.2.11 on 2024-06-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0005_rename_tinan_remata_funcionariu_data_remata"),
    ]

    operations = [
        migrations.RemoveField(model_name="funcionariu", name="tinan_tama",),
    ]
