# Generated by Django 4.2.11 on 2024-06-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0006_remove_funcionariu_tinan_tama"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionariu", old_name="municipality", new_name="Município",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="data_moris", new_name="data_do_nasc",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="data_remata", new_name="data_entrada",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="diresaun", new_name="direção",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="pdf", new_name="documentus",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="fatin_moris", new_name="endereço",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="status", new_name="estatuto",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="foto", new_name="fotografia",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="hela_fatin", new_name="naturalidade",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="naran", new_name="nome_completo",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="nu_kontaktu", new_name="nu_contacto",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="nu", new_name="nu_id",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="pozisaun", new_name="posição",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="seksu", new_name="sexo",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="data_tama", new_name="validade",
        ),
    ]
