# Generated by Django 4.2.11 on 2024-06-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0007_rename_municipality_funcionariu_município_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionariu", old_name="documentus", new_name="documentos",
        ),
        migrations.RenameField(
            model_name="funcionariu", old_name="Município", new_name="município",
        ),
    ]
