# Generated by Django 4.2.11 on 2024-06-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0008_rename_documentus_funcionariu_documentos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Annual", "Annual Leave"),
                            ("Sick", "Sick Leave"),
                            ("Maternity", "Maternity Leave"),
                            ("Paternity", "Paternity Leave"),
                            ("Unpaid", "Unpaid Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("reason", models.TextField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dnct.funcionariu",
                    ),
                ),
            ],
        ),
    ]
