# Generated by Django 4.2.11 on 2024-06-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0011_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateField()),
                ("reviewer", models.CharField(max_length=100)),
                ("ratings", models.DecimalField(decimal_places=1, max_digits=3)),
                ("comments", models.TextField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dnct.funcionariu",
                    ),
                ),
            ],
        ),
    ]
