# Generated by Django 4.2.11 on 2024-06-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0014_salary"),
    ]

    operations = [
        migrations.RemoveField(model_name="funcionariu", name="direção",),
        migrations.AddField(
            model_name="funcionariu",
            name="direction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dnct.department",
            ),
        ),
    ]
