# Generated by Django 4.2.11 on 2024-07-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0015_remove_funcionariu_direção_funcionariu_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="sigla",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
