# Generated by Django 4.2.11 on 2024-07-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0016_department_sigla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="sigla",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Licença", "Licença"),
                    ("Licença Annual", "Licença Annual"),
                    ("Licença do Casamento", "Licença do Casamento"),
                    ("Licença do Estudo", "Licença do Estudo"),
                    ("Licença de Luto", "Licença de Luto"),
                    ("Licença de Maternidade", "Licença de Maternidade"),
                    ("Licença de Paternidade", "Licença de Paternidade"),
                    ("Licença Sem Vencimento", "Licença Sem Vencimento"),
                    ("Doente", "Doente"),
                    ("Licença de Consulta Médica", "Licença de Consulta Médica"),
                    ("Missão de Serviço", "Missão de Serviço"),
                    ("Tolerância de Ponto", "Tolerância de Ponto"),
                ],
                max_length=200,
            ),
        ),
    ]
