# Generated by Django 4.2.11 on 2024-07-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0006_rename_estatus_estatus_estatus"),
        ("dnct", "0017_alter_department_sigla_alter_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariu",
            name="estatus_onoff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom.estatus",
            ),
        ),
    ]
