# Generated by Django 4.2.11 on 2024-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0018_funcionariu_estatus_onoff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
