# Generated by Django 4.2.14 on 2024-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0019_alter_leave_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
