# Generated by Django 4.2.14 on 2024-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0020_leave_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
