# Generated by Django 5.0.7 on 2024-08-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0007_nivel_estudo"),
        ("dnct", "0021_alter_leave_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariu",
            name="nivel_estudo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom.nivel_estudo",
            ),
        ),
    ]
