# Generated by Django 5.0.7 on 2024-08-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0022_funcionariu_nivel_estudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariu",
            name="especialidade",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
