# Generated by Django 5.0.7 on 2024-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnct", "0023_funcionariu_especialidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariu",
            name="grau",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
